# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  clean: true

- task: oc-setup@2
  inputs:
    openshiftService: 'Jeff-Test'

- task: HelmInstaller@1
  displayName: Helm installer
  inputs: 
    helmVersionToInstall: latest

- script: |
    helm repo add bitnami https://charts.bitnami.com/bitnami
    oc project dga-ecomm-dev
    mkdir ~/generated; ls ~/
    helm template redis-cache bitnami/redis -f params-dev.yaml > ~/generated/redis-deploy-dev.yaml
    echo "Generated"; ls ~/generated

- task: oc-cmd@2
  inputs:
    openshiftService: 'Jeff-Test'
    cmd: 'oc -n dga-ecomm-dev apply -f ~/generated/redis-deploy-dev.yaml'
    uselocalOc: true

