# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistentCredentials: true
  clean: true

- task: oc-setup@2
  inputs:
    openshiftService: 'Jeff-Test'

- script: |
    oc -n dga-ecomm-dev apply -f ./templates/service-acct.yaml

